name 'gse'
maintainer 'Arkadiusz Buras'
maintainer_email 'macbury@gmail.com'
license 'all_rights'
description 'Installs/Configures gse'
long_description 'Installs/Configures gse'
version '0.4.13'

depends 'apt'
depends 'build-essential'
depends 'nginx'
depends 'application_ruby'
depends 'nginx_conf'
depends 'postgresql', '~> 4.0.6'
depends 'database', '~> 5.1.2'
depends 'lxmx_oh_my_zsh', '~> 0.5.0'
